### ISSUE TITLE
Add 'information carrier' class (subclass of material entity)

### ISSUE THREAD

**Issue by wdduncan** [OBOFoundry/COB#107]
Per COB workshop:
Add information carrier as subclass of material entity for those entities that "bear" the information.

**Comment by linikujp** [comment]
Suggest to add a term 'digital information barrier' in contrast of the 'physical information barrier'.

**Comment by bpeters42** [comment]
Fleshing this out. 
1) 'material information carrier' = a material entity that has_characteristic some (concretizes some(information content entity)).   
2) to skip the intermediate step, can we introduce a shortcut relation 'carries information'. So that 'material information carrier' 'carries information' some 'information content entity'? I do think all we want to say about how information is maintained in this simplified view is still accurate. Feedback appreciated from @alanruttenberg.

**Comment by wdduncan** [comment]
@linikujp I'm not sure the label 'digital information barrier' would capture all the kinds of information carriers (e.g., lab notebooks).

**Comment by bpeters42** [comment]
Thinking more about this: We just moved 'information representation' into 'characteristic'. that reminded me of some of the original IAO discussions: Some information is hard to say what the material bearer is without referring to a process, such as series of soundwaves transporting human speech, a series of morse code signals, the series of gestures in sign language. 

That makes me want to stick to 'information representation', which will always exist, and leaving it up specific use cases to want to identify the bearer (or not).
