### ISSUE TITLE
Do we need labels for 'in progress' planned processes?

### ISSUE THREAD

**Issue by wdduncan** [OBOFoundry/COB#111]
Per COB workshop:
- perhaps add labels for in-progress planned processes

**Comment by jamesaoverton** [comment]
One aspect of the new planned process modelling that was not discussed today is a constraint of RDF, roughly "monotonicity": Since RDF graphs are timeless, it's better only to add assertions (i.e. triples) and never to retract assertions. In this case, I think it's better not to assert that a planned process is incomplete and then have to retract that assertion later. Instead I would prefer to assert that it's a planned process when it begins, then add an assertion that it's complete once that is true.
