### ISSUE TITLE
Incorrect ID for 'planned process' in cob-to-external

### ISSUE THREAD

**Issue by beckyjackson** [OBOFoundry/COB#191]
In `cob-to-external.tsv`, 'planned process' has the ID COB:0000035:
https://github.com/OBOFoundry/COB/blob/a2f7141c1e30e87352cb656a224fd31027d92701/src/ontology/components/cob-to-external.tsv#L69

... but in the COB file, this is COB:0000082:
https://github.com/OBOFoundry/COB/blob/a2f7141c1e30e87352cb656a224fd31027d92701/cob.owl#L726-L744

In `cob-edit.owl`, COB:0000035 is 'completely executed planned process' so can we either update the ID or label in the external mapping file? I don't know if this mapping was intended to be to the completely-executed one or not. @cmungall ?

**Comment by bpeters42** [comment]
I would bet that this was an accident. But it reminds me that we have to be careful when doing the mapping to OBI, where what we have as 'planned process' is really 'completely executed'. Which further reminds me that we should do an OBI-COB alignment.

**Comment by bpeters42** [comment]
@sebastianduesing - can you check if this is still a thing?

**Comment by cmungall** [comment]
I made the PR but I kept this as exact, I think the misalignment deserves it's own issue

**Comment by sebastianduesing** [comment]
I might be misunderstanding this issue, but I'm not sure that #282 is the right fix. My reading of this issue is:

- In `cob-edit.owl`, COB:0000035 is 'completely executed planned process'.
- In `cob-edit.owl`, COB:0000082 is 'planned process'.
- OBI:0000011, which is called 'planned process' in OBI, is actually equivalent to COB:0000035, 'completely executed planned process'.
- The problem with `cob-to-external.tsv` is that the mapping for OBI:0000011 says it is mapped to a term with the IRI COB:0000035 ('completely executed planned process') but the COB term label in that row is simply 'planned process.'

The change in #282 _changes the IRI to align with the label_ in `cob-to-external.tsv`. I believe that, because we do want OBI:'planned process' to map to COB:'completely executed planned process', the right fix would actually be to _change the label to align with the IRI_.
