### ISSUE TITLE
comments/suggestions

### ISSUE THREAD

**Issue by RLWOHIO** [OBOFoundry/COB#39]
cell definition should probably be changed into:
A material entity that has a plasma membrane and/or cell wall and results from cellular division.
This would account for plant cells.

Should we consider biological pathway as a class above 'biological process'?  Is current definition of biological process inclusive of pathways?  A pathway contains multiple processes.  In systems biology/omics, people normally refer to biological pathways such as those of KEGG/Reactome, not biological processes.

**Comment by addiehl** [comment]
Actually, all cells have a plasma membrane, including all plant cells.  Thus a definition like "A material entity that has a plasma membrane and results from cellular division." is correct for all cells, including plant cells.

Thus 'plant cell' is a subclass of 'cell', defined potentially as simply as "A cell that has a cell wall."

**Comment by addiehl** [comment]
It strikes me that a pathway is really a subtype of a process, rather than the other way around.  Consider the GO term 'cell population proliferation', defined as "The multiplication or reproduction of cells, resulting in the expansion of a cell population."  This is not a pathway, but rather a more general type of process.

Consider GO 'neurotrophin signaling pathway', defined as "A series of molecular signals initiated by the binding of a neurotrophin to a receptor on the surface of a target cell, and ending with regulation of a downstream cellular process, e.g. transcription."  This is clearly a pathway with a beginning and an end.  However, it is also a descendent class of 'cellular process', a general GO term that is not restricted to pathways: "Any process that is carried out at the cellular level, but not necessarily restricted to a single cell."

**Comment by addiehl** [comment]
"In systems biology/omics, people normally refer to biological pathways such as those of KEGG/Reactome, not biological processes."  KEGG and Reactome represent pathways explicitly as their domain, but they do not cover more general biological processes.  Systems biology is focused on the flow of signals and responses, and is thus inherently very pathway oriented; thus the focus on pathway resources rather than GO BP.

**Comment by cmungall** [comment]
agreed

**Comment by RLWOHIO** [comment]
> Actually, all cells have a plasma membrane, including all plant cells. Thus a definition like "A material entity that has a plasma membrane and results from cellular division." is correct for all cells, including plant cells.
I meant to say plasma membrane or plasma membrane + cell wall.  I had a mindset of opposite to genus-differentia.
> Thus 'plant cell' is a subclass of 'cell', defined potentially as simply as "A cell that has a cell wall."
Yes, it now makes sense.

**Comment by RLWOHIO** [comment]
> It strikes me that a pathway is really a subtype of a process, rather than the other way around. Consider the GO term 'cell population proliferation', defined as "The multiplication or reproduction of cells, resulting in the expansion of a cell population." This is not a pathway, but rather a more general type of process.
> 
> Consider GO 'neurotrophin signaling pathway', defined as "A series of molecular signals initiated by the binding of a neurotrophin to a receptor on the surface of a target cell, and ending with regulation of a downstream cellular process, e.g. transcription." This is clearly a pathway with a beginning and an end. However, it is also a descendent class of 'cellular process', a general GO term that is not restricted to pathways: "Any process that is carried out at the cellular level, but not necessarily restricted to a single cell."

Yes, placing pathway under biological process makes sense now.  Pathway is now included in several ontologies defined as biomolecule interactions.   One of them has it under process while others are not as explicit.  I think it would be informative to include pathway in the obo core classes as it is such a prevalent concept.

**Comment by cmungall** [comment]
We could include GO:0007165 signal transduction as an exemplar (we already
have some exemplars like nickel ion)

**Comment by cmungall** [comment]
Closing this, original question about cell walls is aanswered, new ticket for pathway
